name: Release

on:
  push:
    branches:
      - final-project

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install npm dependencies
      - name: Install npm dependencies
        run: npm install
        working-directory: ./pybacktestchain  # Adjusted to point to your main directory with package.json

      # Step 4: Install Python dependencies (single requirements.txt)
      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
        working-directory: ./pybacktestchain  # Single requirements.txt is used

      # Step 5: Run Semantic Release
      - name: Run Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
        working-directory: ./pybacktestchain  # Ensure semantic-release runs from the correct directory
