name: Release

on:
  push:
    branches:
      - final-project

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Debug the current directory
      - name: Debug current directory
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la

      # Step 3: Set up Node.js for npm
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 4: Install npm dependencies
      - name: Install npm dependencies
        working-directory: ./  # Ensure npm looks for package.json here
        run: npm install

      # Step 5: Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install poetry
          poetry install

      # Step 6: Run Semantic Release
      - name: Run Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
